version: "3.9"

services:
  nextjs:
    container_name: mbse-next
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/mbse-chat
    command: npm run start
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always

  storybook:
    container_name: mbse-storybook
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/mbse-chat
    command: npm run storybook -- --no-open --port 6006 --host 0.0.0.0
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 6006
    ports:
      - "6006:6006"
    restart: always

networks:
  default:
    name: mbse-network
