version: "3.9"

services:
  nextjs:
    container_name: mbse-next
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/mbse-chat
    command: npm run start
    environment:
      NODE_ENV: production
    restart: always

  storybook:
    container_name: mbse-storybook
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/mbse-chat
    command: npm run storybook
    environment:
      NODE_ENV: development
    restart: always
